- name: Restart systemd-journald service
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    enabled: true

- name: Restart SSHD service
  ansible.builtin.service:
    name: sshd
    state: restarted
    enabled: true
    when: ansible_facts["distribution"] == "AlmaLinux"
#
- name: Restart SSH service
  ansible.builtin.service:
    name: ssh
    state: restarted
    enabled: true
    when: ansible_facts["distribution"] == "Ubuntu"

- name: Restart systemd service
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  loop: "{{ nlc_default_services }}"
