- name: Fix etc hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ nlc_ipaclient_ipaddress }} {{ nlc_ipaclient_hostname }}.{{ nlc_ipaclient_domain }} {{ nlc_ipaclient_hostname }}"
    state: present

- name: Set hostname as fqdn via systemd
  ansible.builtin.hostname:
    name: "{{ nlc_ipaclient_hostname }}.{{ nlc_ipaclient_domain }}"
    use: systemd

#  ansible.builtin.command:
#    cmd: hostnamectl hostname {{ nlc_ipaclient_hostname | quote }}.{{ nlc_ipaclient_domain | quote }}
#    register: hostname_fqdn

- name: Install IPA Client AlmaLinux
  ansible.builtin.package:
    name: freeipa-client
    state: present
  when: ansible_facts["distribution"] == 'AlmaLinux'

- name: Install IPA Client Ubuntu
  ansible.builtin.package:
    name: freeipa-client
    state: present
  when: ansible_facts["distribution"] == 'Ubuntu'

- name: Set IPA DNS servers
  ansible.builtin.command: resolvectl dns eth0 {{ nlc_ipaclient_server1 }} {{ nlc_ipaclient_server2 }}

- name: Configure IPA Client
  ansible.builtin.command:
    argv:
      - ipa-client-install
      - -U
      - --domain={{ nlc_ipaclient_domain }}
      - --server={{ nlc_ipaclient_server }}
      - -p {{ nlc_ipaclient_principal }}
      - -w {{ nlc_ipaclient_password }}
      - --realm={{ nlc_ipaclient_realm }}
      - --mkhomedir
      - --no-ntp
    creates: /etc/sssd/sssd.conf
