sourcedir /run/chrony-dhcp
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
ntsdumpdir /var/lib/chrony
logdir /var/log/chrony
server 10.8.10.11 iburst
server 10.8.10.12 iburst
server 10.8.10.13 iburst
bindcmdaddress 127.0.0.1
bindcmdaddress ::1
