---
- name: Install GlusterFS
  hosts: glusterfs
  become: true
  block:
    - name: Install GlusterFS package
      ansible.builtin.package:
        name: glusterfs-server
        state: present

    - name: Configure gluster peer probe
      ansible.builtin.command:
        cmd: gluster peer probe {{ item }}
      loop: "{{ groups['glusterfs'] }}"

    - name: Configure gluster volume
      ansible.builtin.command:
        cmd: gluster volume create gv0 replica 3 "{{ groups['glusterfs'] | length }}":/mnt/gluster/brick1/gv0

    - name: Start gluster volume
      ansible.builtin.command:
        cmd: gluster volume start gv0
