---
- name: Setup sudoers service account
  block:
    - name: Create service group
      ansible.builtin.group:
        name: svc_admins
        system: true

    - name: Create service user
      ansible.builtin.user:
        name: svc_deploy
        group: svc_admins
        shell: /bin/bash
        create_home: true
        home: /home/svc_deploy
        state: present

    - name: Copy 20_service-admins
      ansible.builtin.copy:
        src: ../../files/20_service-admins
        dest: /etc/sudoers.d/20_service-admins
        mode: "0644"
        owner: root
        group: root
