- name: chronyd configuration
  ansible.builtin.copy:
    src: files/ntp/chrony.conf
    dest: /etc/chrony.conf
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart systemd service
  when: ansible_facts["distribution"] == "AlmaLinux"
