- name: Configure SSHD settings
  ansible.builtin.copy:
    src: files/ssh/99_acceptenv.conf
    dest: /etc/ssh/sshd_config.d/99_acceptenv.conf
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart SSHD service
  when: ansible_facts["distribution"] == "AlmaLinux"
