- name: Configure systemd settings
  ansible.builtin.copy:
    src: files/systemd/
    dest: /etc/systemd/
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart systemd-journald service
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Configure systemd settings
  ansible.builtin.copy:
    src: files/systemd/
    dest: /lib/systemd/
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart systemd-journald service
  when: ansible_facts["distribution"] == "AlmaLinux"
