- name: Turn off motd, Clean files /etc/legal and /etc/motd
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - src: 10-help-text
      dest: /etc/update-motd.d/10-help-text
    - src: 50-motd-news
      dest: /etc/update-motd.d/50-motd-news
    - src: 60-unminimize
      dest: /etc/update-motd.d/60-unminimize
    - src: 0-isotext
      dest: /etc/update-motd.d/0-isotext
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Add file 900-nlc-profile.sh
  ansible.builtin.template:
    src: 900-nlc-profile.sh.j2
    dest: /etc/profile.d/900-nlc-profile.sh
    owner: root
    group: root
    mode: "0644"
