#!/bin/sh
printf "\n"
printf "WARNING:  Unauthorized access to this system is forbidden and will be\n"
printf "prosecuted by law. By accessing this system, you agree that your\n"
printf "actions may be monitored if unauthorized usage is suspected.\n"
printf "\n"
