---
# System configuration
nlc_default_timezone: UTC

# Service configuration
nlc_default_services:
  - name: ssh
    state: started
    enabled: true
  - name: chronyd
    state: started
    enabled: true
