nlc_default_packages:
  - plocate
  - vim
  - rsync
  - apt-transport-https
  - cron
  - dosfstools
  - less
  - whiptail

nlc_default_purge_packages:
  - lxd-agent-loader
  - lxd-installer
  - unattended-upgrades
